name: AXECore
version: '${project.version}'
main: eu.viberpg.core.Core
api-version: 1.18
load: POSTWORLD
author: Vultron Studios Development
depend:
  - ProtocolLib
  - MythicMobs
  - ModelEngine
  - OpenAudioMc
  - LabyApi
loadbefore:
  - ProtocolLib
  - MythicMobs
  - ModelEngine
  - OpenAudioMc
  - LabyApi
commands:
  language:
    aliases:
      - lang
  voicepack:
    aliases:
      - vp
      - voice
      - voices
  settings:
    aliases: setting
  profiles:
    aliases:
      - profile
  measure:
    permission: axe.measure