name: AXECore
version: '${project.version}'
main: world.axe.axecore.AXECore
api-version: 1.18
load: POSTWORLD
author: Electronic AXE Development
depend:
  - ProtocolLib
  - MythicMobs
  - ModelEngine
  - OpenAudioMc
loadbefore:
  - ProtocolLib
  - MythicMobs
  - ModelEngine
  - OpenAudioMc
commands: